name: Periodic Empty Commit Push

on:
  schedule:
    - cron: '0 * * * *'  # 매시간 정각 실행
  workflow_dispatch:

jobs:
  push-empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check remote URL
        run: git remote -v
      # - name: Configure Git
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     # ✅ 리모트 URL을 PAT 포함된 인증 방식으로 설정
      #     git remote set-url origin https://kbae1230:${{ secrets.PAT_TOKEN }}@github.com/kbae1230/naver_airplane.git

      # - name: Create and push empty commit
      #   run: |
      #     git commit --allow-empty -m "chore: periodic empty commit to keep repo active"
      #     git push origin master
